# -*- coding: utf-8 -*-
"""00_HelloWolrd.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1KL3quedtFpMJMvW7tozw2MJ301o1UcHR
"""

# Este simbolo se utiliza parra comentar el codigo.
print("hola grupo 430 de la carrera tecnica de PROGRAMACION")
#Como consultar el tipo de dato

#print(type("soy un dato str")) # Tipo 'Str'
#print(type(5)) # Tipo 'int'
#print(type(1.5)) # Tipo 'float'
#print(type(3 + 1j)) # Tipo 'complex'
#print(type(true)) # Tipo 'bool'
#print(type(print("Mi primer cadena de texto")))# Tipo 'Nonetype'