# -*- coding: utf-8 -*-
"""02_Operators.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1bCu2zanuvrGpIa4cmi79SSArxOEkYRiD
"""

### operaciones Aritmeticas ###

# Operaciones con enteros
#print(3 + 4)
#print(3 * 4)
#print(3 - 4)
#print(3 / 4)
#print(10 % 3)
#print(10 // 3)
#print(2 ** 3)
#print(2 ** 3 + 3 - 7 )

# Opercaiones con cadenas de texto
# print("hola " + "Phyton " + "¿Que tal?")
# print("hola "+ str(5))

# Operaciones
# print("Hola " * 5)
# print("Hola " * (2 ** 3))


# my_float = 2.5 * 2
# print("hola " * int(my_float))

### operadores comparativos ###

# Operaciones con enteros
#print(3 > 4)
#print(3 < 4)
#print(3 >= 4)
#print(3 <= 4)
#print(3 == 4)
#print(3 != 4)

#  Operaciones con cadenas de texto
#print("Hola" > "Python")
#print("Hola" < "Python")
#print("aaaa" >= "abaa") # Orde ación alfabetica por ASCII
#print(len("aaaa" ) >= len ("abaa")) # Cuenta caracteres
#print("Hola" <= "Python")
#print("Hola" == "Python")
#print("Hola" != "Python")

### Operadores lógicos ###

# Basada el Álgebra de Boole https://es.wikipedia.org/wiki/%C3%81lgebra_de_Boole
print(3 > 4 and "Hola" > "Python")
print(3 > 4 or "Hola" > "Python")
print(3 < 4 and "Hola" < "Python")
print(3 < 4 or "Hola" > "Python")
print(3 < 4 or ("Hola" > "Python" and 4 == 4))
print(not (3 > 4))