# -*- coding: utf-8 -*-
"""04_lists.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1cq6Q0X35VHCU_g40OhAYig9B_aoDlVUC
"""

### listas ###

# Definición

my_list = list() #Lista
my_other_list = [] #Lista

print(len(my_other_list))

my_list = [35, 24, 62, 52, 30, 30, 17]

print(my_list)
print(len(my_list))

my_other_list = [16, 1.75, "Christian", "Rivas"]
print(my_other_list)

print(type(my_list))
print(type(my_other_list))

# Acceso a elementos y busquedas

print(my_other_list[0])
print(my_other_list[1])
print(my_other_list[-1])
print(my_other_list[-4])
print(my_list.count(30))

# print(my_other_list[4]) IndexError
# print(my_other_list[-5]) IndexError

print(my_other_list.index("Christian"))

age, height, name, surnmae, = my_other_list
print(name)

name, height, age, surnmae, = my_other_list[2], my_other_list[1],  my_other_list[0],  my_other_list[3]
print(age)

# Concatenación

print(my_list + my_other_list)
# print(my_list - my_other_list)}}

# Creación, inserción, actualización y eliminación

my_other_list.append("CECyTEM") #Agregar al final
print(my_other_list)

my_other_list.insert(1, "Rojo") #insertar en la posición indicada
print(my_other_list)

my_other_list[1] = "Azul" #reemplazar la posición indicada
print(my_other_list)

my_other_list.remove("Azul") # Eliminar lo seleccionado
print(my_other_list)

my_list.remove(30) # Eliminar el primer caracter que encuentra seleccionado
print(my_list)

print(my_list.pop()) # eliminar e imprimir el que fue eliminado
print(my_list)

my_pop_element = my_list.pop(2)
print(my_pop_element)
print(my_list)

del my_list[2] # elimianr la posición indicada
print(my_list)

# Operaciones con listas

my_new_list = my_list.copy()

my_list.clear()
print(my_list)
print(my_new_list)

my_new_list.reverse()
print(my_new_list)

my_list.sort()
print(my_new_list)

# Sublistas

print(my_new_list[1:3])

# Cambio de tipo

my_list = "Hola Python"
print(my_list)
print(type(my_list))