# -*- coding: utf-8 -*-
"""08_Conditionals.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/108kfU8cPTJ19V9lL5A88f_ubPbvwxPna
"""

### Conditionals ###

# if

my_condition = False

if my_condition: # Es lo mismo que if my_condition == True:
  print("Se ejecuta la condicion del if")

  my_condition = 5 * 5

  if my_condition == 10:
    print("Se ejecuta la cindición del segundo if")

# if, elif else

my_condition = 5 * 5
if my_condition == 10:
  print("Se ejecuta la condicion del segundon if")

  # if, elif, else

if my_condition > 10 and my_condition < 20:
  print("Es mayor que 10 y menor que 20")

elif my_condition == 25:
  print("Es igual a 25")

else:
  print("Es menor o igual que 10 o mayor o igual que 20 o distinto a 25")

print("La ejecucion continua")
# Condicional con inspección de valor

my_string = ""

if not my_string:
  print("Mi cadena de texto es vacia")

if my_string == "Mi cadena de textooooo":
  print("Estas cadenas de texto coinciden")